### ISSUE TITLE
CI Pipeline always fails at "install dependencies" when using cache.

### ISSUE THREAD

**Issue by F-Ross** [dlr-sp/rkopenmdao#10]
See e.g. https://github.com/dlr-sp/rkopenmdao/actions/runs/11009690188/attempts/1. 
When using a cached version of the workflow, the installation of dependencies fails, while when starting from a clean slate, everything works fine. When comparing the output from both, for some reason, different versions of software are (tried to be) installed (e.g. mpi4py@3.1.1 for the failed runs, and mpi4py@4.0.0 for the working run)

**Comment by F-Ross** [comment]
In another example, it didn't find mpirun when using the cache: https://github.com/dlr-sp/rkopenmdao/actions/runs/11029589705/attempts/1.

**Comment by sebasgo** [comment]
I am pretty sure we are good with PR #11. Both failed logs mentioned here read to me as badly restored APT cache.
